"""merge collection to booklist

Revision ID: 41854c02b42e
Revises: add_user_update_pref
Create Date: 2026-04-23 15:29:21.808733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41854c02b42e'
down_revision: Union[str, Sequence[str], None] = 'add_user_update_pref'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booklist', sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.create_index(op.f('ix_booklist_is_default'), 'booklist', ['is_default'], unique=False)
    op.add_column('booklist_item', sa.Column('owner_id', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.create_index(op.f('ix_booklist_item_owner_id'), 'booklist_item', ['owner_id'], unique=False)
    op.add_column('usersearchpreferences', sa.Column('ui_page_size', sa.Integer(), nullable=False, server_default=sa.text('48')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersearchpreferences', 'ui_page_size')
    op.drop_index(op.f('ix_booklist_item_owner_id'), table_name='booklist_item')
    op.drop_column('booklist_item', 'owner_id')
    op.drop_index(op.f('ix_booklist_is_default'), table_name='booklist')
    op.drop_column('booklist', 'is_default')
    # ### end Alembic commands ###
