"""Upgrade schema to support new features

Revision ID: cad7c31b4443
Revises: 
Create Date: 2025-10-18 17:51:16.038877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cad7c31b4443'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- 删除依赖于 FTS 表的旧触发器 ---
    op.execute("DROP TRIGGER IF EXISTS thread_after_update;")
    op.execute("DROP TRIGGER IF EXISTS thread_after_delete;")
    op.execute("DROP TRIGGER IF EXISTS thread_after_insert;")

    # --- 删除 FTS 表 ---
    op.execute("DROP TABLE IF EXISTS thread_fts;")
    
    # --- 删除可能存在的旧表 ---
    op.execute("DROP TABLE IF EXISTS author;")
    op.execute("DROP TABLE IF EXISTS bot_config;")

    # --- 创建新表 ---
    op.create_table('author',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sqlmodel.AutoString(), nullable=False),
    sa.Column('global_name', sqlmodel.AutoString(), nullable=True),
    sa.Column('display_name', sqlmodel.AutoString(), nullable=False),
    sa.Column('avatar_url', sqlmodel.AutoString(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('type_str', sqlmodel.AutoString(), nullable=False),
    sa.Column('value_int', sa.BigInteger(), nullable=True),
    sa.Column('value_float', sa.Float(), nullable=True),
    sa.Column('config_str', sqlmodel.AutoString(), nullable=False),
    sa.Column('tips', sqlmodel.AutoString(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('update_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    
    # --- 修改现有表 ---
    op.add_column('mutex_tag_group', sa.Column('override_tag_name', sqlmodel.AutoString(), nullable=True))
    op.create_index(op.f('ix_mutex_tag_group_override_tag_name'), 'mutex_tag_group', ['override_tag_name'], unique=False)
    
    op.add_column('thread', sa.Column('not_found_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('thread', sa.Column('display_count', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('thread', sa.Column('show_flag', sa.Boolean(), server_default='1', nullable=False))
    op.create_index(op.f('ix_thread_created_at'), 'thread', ['created_at'], unique=False)
    op.create_index(op.f('ix_thread_display_count'), 'thread', ['display_count'], unique=False)
    op.create_index(op.f('ix_thread_not_found_count'), 'thread', ['not_found_count'], unique=False)
    op.create_index(op.f('ix_thread_show_flag'), 'thread', ['show_flag'], unique=False)

    op.add_column('usersearchpreferences', sa.Column('created_after', sqlmodel.AutoString(), nullable=True))
    op.add_column('usersearchpreferences', sa.Column('created_before', sqlmodel.AutoString(), nullable=True))
    op.add_column('usersearchpreferences', sa.Column('active_after', sqlmodel.AutoString(), nullable=True))
    op.add_column('usersearchpreferences', sa.Column('active_before', sqlmodel.AutoString(), nullable=True))
    op.add_column('usersearchpreferences', sa.Column('sort_method', sqlmodel.AutoString(), server_default='comprehensive', nullable=False))
    op.add_column('usersearchpreferences', sa.Column('custom_base_sort', sqlmodel.AutoString(), server_default='comprehensive', nullable=False))

    # 数据迁移
    op.execute("""
        UPDATE usersearchpreferences
        SET
            created_after = strftime('%Y-%m-%d', after_date),
            created_before = strftime('%Y-%m-%d', before_date)
        WHERE after_date IS NOT NULL OR before_date IS NOT NULL;
    """)

    op.drop_column('usersearchpreferences', 'before_date')
    op.drop_column('usersearchpreferences', 'after_date')
    
    # --- 重建 FTS 虚拟表和触发器 ---
    op.execute("""
        CREATE VIRTUAL TABLE IF NOT EXISTS thread_fts USING fts5(
            title,
            first_message_excerpt,
            content='thread',
            content_rowid='id',
            tokenize = 'jieba'
        );
    """)
    op.execute("""
        CREATE TRIGGER IF NOT EXISTS thread_after_insert
        AFTER INSERT ON thread BEGIN
            INSERT INTO thread_fts(rowid, title, first_message_excerpt)
            VALUES (new.id, new.title, new.first_message_excerpt);
        END;
    """)
    op.execute("""
        CREATE TRIGGER IF NOT EXISTS thread_after_delete
        AFTER DELETE ON thread BEGIN
            INSERT INTO thread_fts(thread_fts, rowid, title, first_message_excerpt)
            VALUES ('delete', old.id, old.title, old.first_message_excerpt);
        END;
    """)
    op.execute("""
        CREATE TRIGGER IF NOT EXISTS thread_after_update
        AFTER UPDATE ON thread
        WHEN
            new.title IS NOT old.title OR
            new.first_message_excerpt IS NOT old.first_message_excerpt
        BEGIN
            INSERT INTO thread_fts(thread_fts, rowid, title, first_message_excerpt)
            VALUES ('delete', old.id, old.title, old.first_message_excerpt);
            INSERT INTO thread_fts(rowid, title, first_message_excerpt)
            VALUES (new.id, new.title, new.first_message_excerpt);
        END;
    """)

    # --- FTS 数据回填 ---
    op.execute("""
        INSERT INTO thread_fts(rowid, title, first_message_excerpt)
        SELECT id, title, first_message_excerpt FROM thread;
    """)

    # --- 优化 FTS 表 ---
    op.execute("INSERT INTO thread_fts(thread_fts) VALUES ('optimize');")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- 删除触发器和 FTS 表 ---
    op.execute("DROP TRIGGER IF EXISTS thread_after_update;")
    op.execute("DROP TRIGGER IF EXISTS thread_after_delete;")
    op.execute("DROP TRIGGER IF EXISTS thread_after_insert;")
    op.execute("DROP TABLE IF EXISTS thread_fts;")

    # --- 恢复 UserSearchPreferences 表 ---
    op.add_column('usersearchpreferences', sa.Column('after_date', sa.DATETIME(), nullable=True))
    op.add_column('usersearchpreferences', sa.Column('before_date', sa.DATETIME(), nullable=True))
    
    # 数据回滚
    op.execute("""
        UPDATE usersearchpreferences
        SET
            after_date = date(created_after),
            before_date = date(created_before)
        WHERE created_after IS NOT NULL OR created_before IS NOT NULL;
    """)
    
    op.drop_column('usersearchpreferences', 'custom_base_sort')
    op.drop_column('usersearchpreferences', 'sort_method')
    op.drop_column('usersearchpreferences', 'active_before')
    op.drop_column('usersearchpreferences', 'active_after')
    op.drop_column('usersearchpreferences', 'created_before')
    op.drop_column('usersearchpreferences', 'created_after')
    
    # --- 恢复 Thread 表 ---
    op.drop_index(op.f('ix_thread_show_flag'), table_name='thread')
    op.drop_index(op.f('ix_thread_not_found_count'), table_name='thread')
    op.drop_index(op.f('ix_thread_display_count'), table_name='thread')
    op.drop_index(op.f('ix_thread_created_at'), table_name='thread')
    op.drop_column('thread', 'show_flag')
    op.drop_column('thread', 'display_count')
    op.drop_column('thread', 'not_found_count')
    
    # --- 恢复 MutexTagGroup 表 ---
    op.drop_index(op.f('ix_mutex_tag_group_override_tag_name'), table_name='mutex_tag_group')
    op.drop_column('mutex_tag_group', 'override_tag_name')

    # --- 删除新表 ---
    op.drop_table('bot_config')
    op.drop_table('author')
    
    # --- 在降级结束时，重建旧的 FTS 虚拟表和触发器 ---
    op.execute("""
        CREATE VIRTUAL TABLE IF NOT EXISTS thread_fts USING fts5(
            title,
            first_message_excerpt,
            content='thread',
            content_rowid='id',
            tokenize = 'jieba'
        );
    """)
    op.execute("""
        CREATE TRIGGER IF NOT EXISTS thread_after_insert
        AFTER INSERT ON thread BEGIN
            INSERT INTO thread_fts(rowid, title, first_message_excerpt)
            VALUES (new.id, new.title, new.first_message_excerpt);
        END;
    """)
    op.execute("""
        CREATE TRIGGER IF NOT EXISTS thread_after_delete
        AFTER DELETE ON thread BEGIN
            INSERT INTO thread_fts(thread_fts, rowid, title, first_message_excerpt)
            VALUES ('delete', old.id, old.title, old.first_message_excerpt);
        END;
    """)
    op.execute("""
        CREATE TRIGGER IF NOT EXISTS thread_after_update
        AFTER UPDATE ON thread BEGIN
            INSERT INTO thread_fts(thread_fts, rowid, title, first_message_excerpt)
            VALUES ('delete', old.id, old.title, old.first_message_excerpt);
            INSERT INTO thread_fts(rowid, title, first_message_excerpt)
            VALUES (new.id, new.title, new.first_message_excerpt);
        END;
    """)

    # --- FTS 数据回填 ---
    op.execute("""
        INSERT INTO thread_fts(rowid, title, first_message_excerpt)
        SELECT id, title, first_message_excerpt FROM thread;
    """)

    # --- 优化 FTS 表 ---
    op.execute("INSERT INTO thread_fts(thread_fts) VALUES ('optimize');")

    # ### end Alembic commands ###